### ISSUE TITLE
vmrun.exe missing error

### ISSUE THREAD

**Issue by pessimism** [pecigonzalo/docker-machine-vmwareworkstation#40] opened 2017-02-14 13:00 UTC
VMware workstation 12.5 pro doesn't include vmrun.exe anymore.  You have to download and install the VIX API SDK (VMware-VIX-1.15.0-2985596.exe) from their website to get it.  You then need another path entry on start.sh like below:

export PATH="$PATH:/c/Program Files (x86)/VMware/VMware Workstation:/c/Program Files (x86)/VMware/VMware VIX"

**Comment by pecigonzalo** [comment] 2017-02-20 21:26
Ill start looking into this ASAP

**Comment by ray-g** [comment] 2017-03-10 06:05
I'm using `VMware Workstation Pro 12.5.0 build-4352439`, but I have `vmrun.exe` in my VMware Workstation path.

```text
C:\Program Files (x86)\VMware\VMware Workstation>dir vmrun.exe

 Directory of C:\Program Files (x86)\VMware\VMware Workstation

09/06/2016  07:30 PM           478,280 vmrun.exe
               1 File(s)        478,280 bytes
               0 Dir(s)  112,708,055,040 bytes free

C:\Program Files (x86)\VMware\VMware Workstation>vmrun.exe

vmrun version 1.15.4 build-4352439
```

BTW, I saw that 12.5.3 is available for upgrade. I'll upgrade my VMware Workstation and check it again. Will update my result later.

**Comment by ray-g** [comment] 2017-03-10 06:25
Upgraded to `12.5.3 build-5115892`. it's still there, and has been upgraded as well. `vmrun version 1.15.7 build-5115892`

**Comment by StefanScherer** [comment] 2017-03-10 06:48
I can confirm that my VMware Workstation Pro 12.5 installation has `C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe`.

**Comment by pecigonzalo** [comment] 2017-08-03 08:59
@pessimism Ill close this issue as there were no more updates from you. Please comment if you believe this needs to be reopened.

**Closed as completed by pecigonzalo** 2017-08-03 08:59 UTC

**Comment by Karrq** [comment] 2019-07-18 09:33
This also happens with VMWare Workstation 15 Player.

This is because the VIX API (vmrun) isn't included in VMWare Workstation 15 Player.
See [this](https://communities.vmware.com/thread/597920) guide to setup the VIX API on Player.

**Comment by roberdaniel** [comment] 2019-10-19 01:49
Hi all
I confirm that only having Vmware Player 15 is not enough at all.
seemingly your tool is looking in the registry for a path that doesn't exist and tool that doesn't exist.
```
Unable to read registry key SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\vmware.exe\Path
Error finding VMware root: The system cannot find the file specified.
File not found: 'vmrun.exe'
Unable to read registry key SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\vmware.exe\Path
Error finding VMware root: The system cannot find the file specified.
File not found: 'vmware-vdiskmanager.exe'
This is a Docker Machine plugin binary.
Plugin binaries are not intended to be invoked directly.
Please use this plugin through the main 'docker-machine' binary.
(API version: 1)

```

1. In my registry there isn't a path to vmware.exe, instead is a path to vmplayer.exe
2. Also there is not such tools called vmrun.exe and vmware-vdiskmanager.exe.

I've downloaded and installed Wix api as suggested by Karrq, now I have vmrun.exe but in another folder :(
I've downloaded VirtualDisk development kit https://my.vmware.com/web/vmware/details?downloadGroup=VDDK67U3&productId=742
Now I have this second executable either but I don't know where to put it.

Any idea how to integrate all ?

Regards

**Comment by roberdaniel** [comment] 2019-10-19 04:20
Nevermind, I've decided to download the full Vmware Workstation Pro and with it it seems to be working ok.
Please instruct in a readme file/prerequisites file that people don't use "Player" versions of VMware to avoid problems.
Regards

**Comment by pecigonzalo** [comment] 2019-10-19 09:32
It says already not to use it
